name: deploy-trader-schedule

# Controls when the workflow will run
on:
  # Run on pushes (including merges) to main
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ALPACA_API_KEY_ID: ${{ secrets.ALPACA_API_KEY_ID }}
      ALPACA_API_SECRET_KEY: ${{ secrets.ALPACA_API_SECRET_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          logout: true

      - name: Build docker images
        run: |
          # Fails the build if anything returns non-zero
          set -e
          # Echo commands to the console
          set -x

          # Build schedule and worker images
          docker build -t ${{ secrets.DOCKER_URL }}/alpaca-trader-schedule:${{ github.sha }} -f Dockerfile .

      - name: Push Docker Images
        run: |
          # push docker images to dockerhub
          docker push ${{ secrets.DOCKER_URL }}/alpaca-trader-schedule:${{ github.sha }}

      - name: Checkout config manifests
        uses: actions/checkout@v3
        with:
          repository: stmcallister/alpaca-trader-config
          path: config-repo
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true

      - name: Configure and Deploy Cluster
        run: |
          # Alter k8s.yaml to sed the version
          sed -i'' -e 's/DOCKER_URL/${{ secrets.DOCKER_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' -e config-repo/config/deployment.yaml

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "stmcallister@gmail.com"

      - name: Commit changes in config repo and push to render_prod
        run: |
          # add, commit, and push changes to render_prod branch
          git add -A 
          git commit -m "Updating k8s manifest from ref: ${{ github.sha }}"
          git push -u --force origin HEAD:render_prod
        working-directory: config-repo
